name: generate fonts

on:
  push:
    tags:
      - 'v*.*.*'

concurrency: generate-fonts

jobs:
  patch1:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        styles: ['fixed', 'fixed-slab', 'mono', 'mono-slab']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
        variants:
          [
            'regular',
            'italic',
            'bold',
            'bolditalic',
            'semibold',
            'semibolditalic',
            'light',
            'lightitalic',
            'extralight',
            'extralightitalic',
          ]
    env:
      FILENAME: 'sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}'
      NERD_FONTS_VERSION: v2.2.2
    steps:
      - uses: actions/checkout@v3

      # credits: https://github.com/adam7/delugia-code/blob/411f2aecdef35d6bb92776d26bb5efe4ee799e0a/.github/workflows/ci.yaml#L77-L100
      - name: Fetch FontForge
        run: |
          sudo apt install software-properties-common python3-fontforge fuse -y -q
          curl -L "https://github.com/fontforge/fontforge/releases/download/20220308/FontForge-2022-03-08-582bd41-x86_64.AppImage" \
            --output fontforge
          chmod u+x fontforge
          echo Try appimage
          ./fontforge --version
          echo `pwd` >> $GITHUB_PATH
          echo Try appimage with path
          fontforge --version
      - name: Get Font Patcher
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'ryanoasis/nerd-fonts'
          tag: ${{ env.NERD_FONTS_VERSION }}
          fileName: 'FontPatcher.zip'
      - name: Open Font Patcher release
        run: |
          unzip FontPatcher.zip

      - run: tree .
      - name: Get the latest version of Sarasa Gothic
        run: |
          LATEST_TAG=$(echo ${{ github.ref_name }} | cut -d '-' -f 1)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo LATEST_TAG is ${{ env.LATEST_TAG }}
          echo "LATEST_VERSION=${LATEST_TAG:1}" >> $GITHUB_ENV
          echo LATEST_VERSION is ${{ env.LATEST_VERSION }}
      - name: Download latest version of Sarasa Gothic from GitHub release page
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'be5invis/Sarasa-Gothic'
          tag: ${{ env.LATEST_TAG }}
          fileName: 'sarasa-gothic-ttf-${{ env.LATEST_VERSION }}.7z'
          out-file-path: sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install configparser
        run: pip install configparser
      - run: ls -l
      - name: patch font
        run: fontforge -script "${PWD}/font-patcher" --adjust-line-height --careful --complete --no-progressbars --quiet "${PWD}/${FILENAME}.ttf" --outputdir "${PWD}"
      - run: ls -l
      - name: rename patched font files
        run: mv *Complete.ttf "${FILENAME}-nerd-font.ttf"
      - run: ls -l
      - name: install fonttools
        run: pip install fonttools
      - name: correcting xAvgCharWidth to fix alignment issue
        run: |
          ttx -t "OS/2" "${FILENAME}.ttf"
          ttx -t "OS/2" "${FILENAME}-nerd-font.ttf"
          ls -l *.ttx
          cat "${FILENAME}.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          original_x_avg_char_width="$(grep xAvgCharWidth "${FILENAME}.ttx" | cut -d '"' -f 2)"
          echo original xAvgCharWidth is $original_x_avg_char_width
          sed -i "s/xAvgCharWidth value=\"[0-9]\+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" "${FILENAME}-nerd-font.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          mv "${FILENAME}-nerd-font.ttf" "${FILENAME}-nerd-font.original.ttf"
          ttx -o "${FILENAME}-nerd-font.ttf" -m "${FILENAME}-nerd-font.original.ttf" "${FILENAME}-nerd-font.ttx"
      - name: build hdmx table to fix alignment issue
        run: python build-hdmx-for-sarasa.py "${FILENAME}-nerd-font.ttf"
      - name: correct TTF font family name
        run: python correct-ttf-font-family-name.py "${FILENAME}-nerd-font.ttf"
      - name: upload patched font
        uses: actions/upload-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  patch2:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        styles: ['term', 'term-slab', 'gothic', 'ui']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
        variants:
          [
            'regular',
            'italic',
            'bold',
            'bolditalic',
            'semibold',
            'semibolditalic',
            'light',
            'lightitalic',
            'extralight',
            'extralightitalic',
          ]
    env:
      FILENAME: 'sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}'
      NERD_FONTS_VERSION: v2.2.2
    steps:
      - uses: actions/checkout@v3

      # credits: https://github.com/adam7/delugia-code/blob/411f2aecdef35d6bb92776d26bb5efe4ee799e0a/.github/workflows/ci.yaml#L77-L100
      - name: Fetch FontForge
        run: |
          sudo apt install software-properties-common python3-fontforge fuse -y -q
          curl -L "https://github.com/fontforge/fontforge/releases/download/20220308/FontForge-2022-03-08-582bd41-x86_64.AppImage" \
            --output fontforge
          chmod u+x fontforge
          echo Try appimage
          ./fontforge --version
          echo `pwd` >> $GITHUB_PATH
          echo Try appimage with path
          fontforge --version
      - name: Get Font Patcher
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'ryanoasis/nerd-fonts'
          tag: ${{ env.NERD_FONTS_VERSION }}
          fileName: 'FontPatcher.zip'
      - name: Open Font Patcher release
        run: |
          unzip FontPatcher.zip

      - run: tree .
      - name: Get the latest version of Sarasa Gothic
        run: |
          LATEST_TAG=$(echo ${{ github.ref_name }} | cut -d '-' -f 1)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo LATEST_TAG is ${{ env.LATEST_TAG }}
          echo "LATEST_VERSION=${LATEST_TAG:1}" >> $GITHUB_ENV
          echo LATEST_VERSION is ${{ env.LATEST_VERSION }}
      - name: Download latest version of Sarasa Gothic from GitHub release page
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'be5invis/Sarasa-Gothic'
          tag: ${{ env.LATEST_TAG }}
          fileName: 'sarasa-gothic-ttf-${{ env.LATEST_VERSION }}.7z'
          out-file-path: sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install configparser
        run: pip install configparser
      - run: ls -l
      - name: patch font
        run: fontforge -script "${PWD}/font-patcher" --adjust-line-height --careful --complete --no-progressbars --quiet "${PWD}/${FILENAME}.ttf" --outputdir "${PWD}"
      - run: ls -l
      - name: rename patched font files
        run: mv *Complete.ttf "${FILENAME}-nerd-font.ttf"
      - run: ls -l
      - name: install fonttools
        run: pip install fonttools
      - name: correcting xAvgCharWidth to fix alignment issue
        run: |
          ttx -t "OS/2" "${FILENAME}.ttf"
          ttx -t "OS/2" "${FILENAME}-nerd-font.ttf"
          ls -l *.ttx
          cat "${FILENAME}.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          original_x_avg_char_width="$(grep xAvgCharWidth "${FILENAME}.ttx" | cut -d '"' -f 2)"
          echo original xAvgCharWidth is $original_x_avg_char_width
          sed -i "s/xAvgCharWidth value=\"[0-9]\+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" "${FILENAME}-nerd-font.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          mv "${FILENAME}-nerd-font.ttf" "${FILENAME}-nerd-font.original.ttf"
          ttx -o "${FILENAME}-nerd-font.ttf" -m "${FILENAME}-nerd-font.original.ttf" "${FILENAME}-nerd-font.ttx"
      - name: build hdmx table to fix alignment issue
        run: python build-hdmx-for-sarasa.py "${FILENAME}-nerd-font.ttf"
      - name: correct TTF font family name
        run: python correct-ttf-font-family-name.py "${FILENAME}-nerd-font.ttf"
      - name: Upload patched font
        uses: actions/upload-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  zip:
    needs: [patch1, patch2]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        styles: ['fixed', 'fixed-slab', 'mono', 'mono-slab', 'term', 'term-slab', 'gothic', 'ui']
        orthographies: ['cl', 'hc', 'j', 'k', 'sc', 'tc']
    steps:
      # start of part generated by `generate-download-patched-fonts` script
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-regular font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-italic font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bold font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bolditalic font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibold font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibolditalic font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-light font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-lightitalic font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralight font
      - uses: actions/download-artifact@v3
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralightitalic font
      # end of part generated by `generate-download-patched-fonts` script

      - run: ls -l
      - name: zip patched font files
        run: zip -r sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-*-nerd-font.ttf
      - run: ls -l
      - name: upload zip
        uses: actions/upload-artifact@v3
        with:
          name: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip

  release:
    needs: zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l

      # start of part generated by `generate-download-patched-zips` script
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-fixed-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-mono-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-term-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-gothic-tc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-cl-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-hc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-j-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-k-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-sc-nerd-font.zip
      - uses: actions/download-artifact@v3
        with:
          name: sarasa-ui-tc-nerd-font.zip
      # end of part generated by `generate-download-patched-zips` script

      - run: ls -l
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
